### ISSUE TITLE
Get list of issues for a defined milestone to generate release notes

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/CKTools#3]
- [x] Connect to Github API with python
- [x] Get milestone for current release for each mod
- [x] Get list of closed issues for milestone
- [x] Display list of issues into a file in markdown, broken by issue type (bug/enhancement)
- [x] Add markdown file to release notes folder in github

**Comment by SkyrimLL** [comment]
Use this github python API:
https://pygithub.readthedocs.io/en/latest/reference.html

Example of similarcode in groovy:
https://github.com/arturbosch/gitlab-milestone-report/blob/master/src/main/groovy/milestone-report.groovy
